### ISSUE TITLE
Module did not self-register

### ISSUE THREAD

**Issue by itsdsk** [WebPlatformForEmbedded/node-wpe-webgl#4]
On Raspberry Pi 3 with node 8.9.4, jessie:

```
module.js:672
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: Module did not self-register.
    at Object.Module._extensions..node (module.js:672:18)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/src/app/node_modules/wpe-webgl/gles2.js:1:75)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
```

gpu_mem is set to 196 and the results are the same with the new graphics driver (dt_overlay = vc4-kms-v3d)

**Comment by basvanmeurs** [comment]
I've seen this error before and actually thought I had fixed it in https://github.com/WebPlatformForEmbedded/node-wpe-webgl/commit/12c79aa71942cb51b908bffc10e244d48dce4cef
Are you sure that these changes are in your binding.gyp file?

Can you please check the output of the command` PKG_CONFIG_PATH=/opt/vc/lib/pkgconfig/ pkg-config brcmglesv2 brcmegl --libs --silence-errors`? More specifically, please check if the directory /opt/vc/lib/pkgconfig/ contains the broadcom libraries brcmglesv2 brcmegl.
