### ISSUE TITLE
windows installation fails:

### ISSUE THREAD

**Issue by Spongman** [WebPlatformForEmbedded/node-wpe-webgl#5]
```
PS C:\play\nodegl> yarn add -D wpe-webgl
yarn add v1.5.1
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[1/1] ⠁ wpe-webgl: not ok
error An unexpected error occurred: "C:\\play\
odegl\
ode_modules\\wpe-webgl: Command failed.
Exit code: 1
Command: C:\\WINDOWS\\system32\\cmd.exe
Arguments: /d /s /c node-gyp rebuild
Directory: C:\\play\
odegl\
ode_modules\\wpe-webgl
Output:
C:\\play\
odegl\
ode_modules\\wpe-webgl>if not defined npm_config_node_gyp (node \"C:\\Program Files\
odejs\
ode_modules\
pm\\bin\
ode-gyp-bin\\\\..\\..\
ode_modules\
ode-gyp\\bin\
ode-gyp.js\" rebuild )  else (node \"\" rebuild )
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@9.9.0 | win32 | x64
gyp info spawn C:\\Python27\\python.EXE
gyp info spawn args [ 'C:\\\\Program Files\\\
odejs\\\
ode_modules\\\
pm\\\
ode_modules\\\
ode-gyp\\\\gyp\\\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\\\play\\\
odegl\\\
ode_modules\\\\wpe-webgl\\\\build\\\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\\\Program Files\\\
odejs\\\
ode_modules\\\
pm\\\
ode_modules\\\
ode-gyp\\\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\\\Users\\\\piersh.DFCN\\\\.node-gyp\\\\9.9.0\\\\include\\\
ode\\\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\\\Users\\\\piersh.DFCN\\\\.node-gyp\\\\9.9.0',
gyp info spawn args   '-Dnode_gyp_dir=C:\\\\Program Files\\\
odejs\\\
ode_modules\\\
pm\\\
ode_modules\\\
ode-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\piersh.DFCN\\\\.node-gyp\\\\9.9.0\\\\<(target_arch)\\\
ode.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\\\play\\\
odegl\\\
ode_modules\\\\wpe-webgl',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\\\play\\\
odegl\\\
ode_modules\\\\wpe-webgl\\\\build',
gyp info spawn args   '-Goutput_dir=.' ]
'pkg-config' is not recognized as an internal or external command,\r
operable program or batch file.\r
gyp: Call to 'pkg-config glesv2 egl --libs --silence-errors | grep bcm || true' returned exit status 255 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\\Program Files\
odejs\
ode_modules\
pm\
ode_modules\
ode-gyp\\lib\\configure.js:336:16)
gyp ERR! stack     at ChildProcess.emit (events.js:180:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command \"C:\\\\Program Files\\\
odejs\\\
ode.exe\" \"C:\\\\Program Files\\\
odejs\\\
ode_modules\\\
pm\\\
ode_modules\\\
ode-gyp\\\\bin\\\
ode-gyp.js\" \"rebuild\"
gyp ERR! cwd C:\\play\
odegl\
ode_modules\\wpe-webgl
gyp ERR! node -v v9.9.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok".
info If you think this is a bug, please open a bug report with the information provided in "C:\\play\
odegl\\yarn-error.log".
```

**Comment by Mapaler** [comment]
Me too,  I'm trying to install a Windows version pkg-config and grep, but i's not useful.
And, I can't install this in linux.
![Screenshot 2019-07-09 18 38 17](https://user-images.githubusercontent.com/6565860/60881683-c700bb80-a278-11e9-82fc-b62fa8fd807f.png)
